// AUTO-GENERATED by scripts/generate-idea-icons.ts — do not edit by hand.
// Mapping source: scripts/idea-icon-mappings.json (paths relative to the
// intellij-community platform/icons/src checkout passed via --source).
// Keys are icon export display names resolved by createIconComponent.

import archiveLight from "./idea/expui/fileTypes/archive.svg?url";
import archiveDark from "./idea/expui/fileTypes/archive_dark.svg?url";
import arrowClockwiseLight from "./idea/expui/general/redo.svg?url";
import arrowClockwiseDark from "./idea/expui/general/redo_dark.svg?url";
import arrowCounterClockwiseLight from "./idea/expui/general/undo.svg?url";
import arrowCounterClockwiseDark from "./idea/expui/general/undo_dark.svg?url";
import arrowDownLight from "./idea/expui/general/down.svg?url";
import arrowDownDark from "./idea/expui/general/down_dark.svg?url";
import arrowLeftLight from "./idea/expui/general/left.svg?url";
import arrowLeftDark from "./idea/expui/general/left_dark.svg?url";
import arrowRightLight from "./idea/expui/general/right.svg?url";
import arrowRightDark from "./idea/expui/general/right_dark.svg?url";
import arrowSquareOutLight from "./idea/expui/ide/externalLink.svg?url";
import arrowSquareOutDark from "./idea/expui/ide/externalLink_dark.svg?url";
import arrowUpLight from "./idea/expui/general/up.svg?url";
import arrowUpDark from "./idea/expui/general/up_dark.svg?url";
import balloonErrorLight from "./idea/expui/status/error.svg?url";
import balloonErrorDark from "./idea/expui/status/error_dark.svg?url";
import bellLight from "./idea/expui/toolwindows/notifications.svg?url";
import bellDark from "./idea/expui/toolwindows/notifications_dark.svg?url";
import bellLargeLight from "./idea/expui/toolwindows/notifications@20x20.svg?url";
import bellLargeDark from "./idea/expui/toolwindows/notifications@20x20_dark.svg?url";
import bookmarkLight from "./idea/expui/bookmarks/bookmark.svg?url";
import bookmarkDark from "./idea/expui/bookmarks/bookmark_dark.svg?url";
import bookOpenLight from "./idea/expui/toolwindows/documentation.svg?url";
import bookOpenDark from "./idea/expui/toolwindows/documentation_dark.svg?url";
import bugLight from "./idea/expui/run/debug.svg?url";
import bugDark from "./idea/expui/run/debug_dark.svg?url";
import caretDownLight from "./idea/expui/general/chevronDown.svg?url";
import caretDownDark from "./idea/expui/general/chevronDown_dark.svg?url";
import caretLeftLight from "./idea/expui/general/chevronLeft.svg?url";
import caretLeftDark from "./idea/expui/general/chevronLeft_dark.svg?url";
import caretRightLight from "./idea/expui/general/chevronRight.svg?url";
import caretRightDark from "./idea/expui/general/chevronRight_dark.svg?url";
import caretUpLight from "./idea/expui/general/chevronUp.svg?url";
import caretUpDark from "./idea/expui/general/chevronUp_dark.svg?url";
import chatCircleTextLight from "./idea/expui/toolwindows/messages.svg?url";
import chatCircleTextDark from "./idea/expui/toolwindows/messages_dark.svg?url";
import checkCircleLight from "./idea/expui/general/successDialog.svg?url";
import checkCircleDark from "./idea/expui/general/successDialog_dark.svg?url";
import checkLight from "./idea/expui/general/greenCheckmark.svg?url";
import checkDark from "./idea/expui/general/greenCheckmark_dark.svg?url";
import chevronDownLight from "./idea/expui/general/chevronDown.svg?url";
import chevronDownDark from "./idea/expui/general/chevronDown_dark.svg?url";
import chevronLeftLight from "./idea/expui/general/chevronLeft.svg?url";
import chevronLeftDark from "./idea/expui/general/chevronLeft_dark.svg?url";
import chevronRightLight from "./idea/expui/general/chevronRight.svg?url";
import chevronRightDark from "./idea/expui/general/chevronRight_dark.svg?url";
import chevronUpLight from "./idea/expui/general/chevronUp.svg?url";
import chevronUpDark from "./idea/expui/general/chevronUp_dark.svg?url";
import clockCounterClockwiseLight from "./idea/expui/general/history.svg?url";
import clockCounterClockwiseDark from "./idea/expui/general/history_dark.svg?url";
import columnsLight from "./idea/expui/general/splitVertically.svg?url";
import columnsDark from "./idea/expui/general/splitVertically_dark.svg?url";
import copyLight from "./idea/expui/general/copy.svg?url";
import copyDark from "./idea/expui/general/copy_dark.svg?url";
import copySimpleLight from "./idea/expui/general/copy.svg?url";
import copySimpleDark from "./idea/expui/general/copy_dark.svg?url";
import databaseLight from "./idea/expui/toolwindows/toolWindowDataView.svg?url";
import databaseDark from "./idea/expui/toolwindows/toolWindowDataView_dark.svg?url";
import dotsThreeLight from "./idea/expui/general/moreHorizontal.svg?url";
import dotsThreeDark from "./idea/expui/general/moreHorizontal_dark.svg?url";
import downloadLight from "./idea/expui/general/download.svg?url";
import downloadDark from "./idea/expui/general/download_dark.svg?url";
import downloadSimpleLight from "./idea/expui/general/download.svg?url";
import downloadSimpleDark from "./idea/expui/general/download_dark.svg?url";
import eyeLight from "./idea/expui/general/show.svg?url";
import eyeDark from "./idea/expui/general/show_dark.svg?url";
import eyeSlashLight from "./idea/expui/general/hide.svg?url";
import eyeSlashDark from "./idea/expui/general/hide_dark.svg?url";
import fileLight from "./idea/fileTypes/text.svg?url";
import filePlusLight from "./idea/expui/actions/addFile.svg?url";
import filePlusDark from "./idea/expui/actions/addFile_dark.svg?url";
import filesLight from "./idea/expui/toolwindows/project.svg?url";
import filesDark from "./idea/expui/toolwindows/project_dark.svg?url";
import filesLargeLight from "./idea/expui/toolwindows/project@20x20.svg?url";
import filesLargeDark from "./idea/expui/toolwindows/project@20x20_dark.svg?url";
import fileTextLight from "./idea/fileTypes/text.svg?url";
import floppyDiskLight from "./idea/expui/general/save.svg?url";
import floppyDiskDark from "./idea/expui/general/save_dark.svg?url";
import folderLight from "./idea/expui/nodes/folder.svg?url";
import folderDark from "./idea/expui/nodes/folder_dark.svg?url";
import folderPlusLight from "./idea/expui/actions/newFolder.svg?url";
import folderPlusDark from "./idea/expui/actions/newFolder_dark.svg?url";
import functionLight from "./idea/expui/nodes/function.svg?url";
import functionDark from "./idea/expui/nodes/function_dark.svg?url";
import funnelLight from "./idea/expui/general/filter.svg?url";
import funnelDark from "./idea/expui/general/filter_dark.svg?url";
import gearLight from "./idea/expui/general/settings.svg?url";
import gearDark from "./idea/expui/general/settings_dark.svg?url";
import gearLargeLight from "./idea/expui/general/settings@20x20.svg?url";
import gearLargeDark from "./idea/expui/general/settings@20x20_dark.svg?url";
import gearSixLight from "./idea/expui/general/settings.svg?url";
import gearSixDark from "./idea/expui/general/settings_dark.svg?url";
import gitBranchLight from "./idea/vcs/branch.svg?url";
import gitBranchDark from "./idea/vcs/branch_dark.svg?url";
import gitCommitLight from "./idea/expui/vcs/commit.svg?url";
import gitCommitDark from "./idea/expui/vcs/commit_dark.svg?url";
import gitCommitLargeLight from "./idea/expui/toolwindows/commit@20x20.svg?url";
import gitCommitLargeDark from "./idea/expui/toolwindows/commit@20x20_dark.svg?url";
import gitDiffLight from "./idea/expui/vcs/diff.svg?url";
import gitDiffDark from "./idea/expui/vcs/diff_dark.svg?url";
import gitGraphLight from "./idea/expui/toolwindows/vcs.svg?url";
import gitGraphDark from "./idea/expui/toolwindows/vcs_dark.svg?url";
import gitGraphLargeLight from "./idea/expui/toolwindows/vcs@20x20.svg?url";
import gitGraphLargeDark from "./idea/expui/toolwindows/vcs@20x20_dark.svg?url";
import gitMergeLight from "./idea/expui/vcs/merge.svg?url";
import gitMergeDark from "./idea/expui/vcs/merge_dark.svg?url";
import globeHemisphereWestLight from "./idea/expui/toolwindows/web.svg?url";
import globeHemisphereWestDark from "./idea/expui/toolwindows/web_dark.svg?url";
import globeLight from "./idea/expui/toolwindows/web.svg?url";
import globeDark from "./idea/expui/toolwindows/web_dark.svg?url";
import hashLight from "./idea/expui/general/hashtag.svg?url";
import hashDark from "./idea/expui/general/hashtag_dark.svg?url";
import houseLight from "./idea/expui/javaee/home.svg?url";
import houseDark from "./idea/expui/javaee/home_dark.svg?url";
import imageLight from "./idea/expui/fileTypes/image.svg?url";
import imageDark from "./idea/expui/fileTypes/image_dark.svg?url";
import infoLight from "./idea/expui/general/informationDialog.svg?url";
import infoDark from "./idea/expui/general/informationDialog_dark.svg?url";
import keyboardLight from "./idea/expui/general/keyboard.svg?url";
import keyboardDark from "./idea/expui/general/keyboard_dark.svg?url";
import lightbulbLight from "./idea/expui/actions/realIntentionBulb.svg?url";
import lightbulbDark from "./idea/expui/actions/realIntentionBulb_dark.svg?url";
import lightningLight from "./idea/expui/actions/lightning.svg?url";
import lightningDark from "./idea/expui/actions/lightning_dark.svg?url";
import lockLight from "./idea/expui/general/locked.svg?url";
import lockDark from "./idea/expui/general/locked_dark.svg?url";
import lockOpenLight from "./idea/expui/general/unlocked.svg?url";
import lockOpenDark from "./idea/expui/general/unlocked_dark.svg?url";
import magnifyingGlassLight from "./idea/expui/general/search.svg?url";
import magnifyingGlassDark from "./idea/expui/general/search_dark.svg?url";
import magnifyingGlassLargeLight from "./idea/expui/general/search@20x20.svg?url";
import magnifyingGlassLargeDark from "./idea/expui/general/search@20x20_dark.svg?url";
import magnifyingGlassMinusLight from "./idea/expui/image/zoomOut.svg?url";
import magnifyingGlassMinusDark from "./idea/expui/image/zoomOut_dark.svg?url";
import magnifyingGlassPlusLight from "./idea/expui/image/zoomIn.svg?url";
import magnifyingGlassPlusDark from "./idea/expui/image/zoomIn_dark.svg?url";
import menuLight from "./idea/expui/general/menu.svg?url";
import menuDark from "./idea/expui/general/menu_dark.svg?url";
import menuLargeLight from "./idea/expui/general/windowsMenu@20x20.svg?url";
import menuLargeDark from "./idea/expui/general/windowsMenu@20x20_dark.svg?url";
import minusLight from "./idea/expui/general/remove.svg?url";
import minusDark from "./idea/expui/general/remove_dark.svg?url";
import monitorLight from "./idea/expui/nodes/desktop.svg?url";
import monitorDark from "./idea/expui/nodes/desktop_dark.svg?url";
import openExternalLight from "./idea/expui/ide/externalLink.svg?url";
import openExternalDark from "./idea/expui/ide/externalLink_dark.svg?url";
import paletteLight from "./idea/expui/toolwindows/palette.svg?url";
import paletteDark from "./idea/expui/toolwindows/palette_dark.svg?url";
import pauseLight from "./idea/expui/run/pause.svg?url";
import pauseDark from "./idea/expui/run/pause_dark.svg?url";
import pencilLight from "./idea/expui/general/edit.svg?url";
import pencilDark from "./idea/expui/general/edit_dark.svg?url";
import pencilLineLight from "./idea/expui/general/edit.svg?url";
import pencilLineDark from "./idea/expui/general/edit_dark.svg?url";
import pencilSimpleLight from "./idea/expui/general/edit.svg?url";
import pencilSimpleDark from "./idea/expui/general/edit_dark.svg?url";
import pencilSimpleLineLight from "./idea/expui/general/edit.svg?url";
import pencilSimpleLineDark from "./idea/expui/general/edit_dark.svg?url";
import penLight from "./idea/expui/general/edit.svg?url";
import penDark from "./idea/expui/general/edit_dark.svg?url";
import playLight from "./idea/expui/run/run.svg?url";
import playDark from "./idea/expui/run/run_dark.svg?url";
import plusLight from "./idea/expui/general/add.svg?url";
import plusDark from "./idea/expui/general/add_dark.svg?url";
import problemsToolWindowLight from "./idea/expui/toolwindows/problems.svg?url";
import problemsToolWindowDark from "./idea/expui/toolwindows/problems_dark.svg?url";
import problemsToolWindowLargeLight from "./idea/expui/toolwindows/problems@20x20.svg?url";
import problemsToolWindowLargeDark from "./idea/expui/toolwindows/problems@20x20_dark.svg?url";
import pushPinLight from "./idea/expui/general/pin.svg?url";
import pushPinDark from "./idea/expui/general/pin_dark.svg?url";
import questionLight from "./idea/expui/general/questionDialog.svg?url";
import questionDark from "./idea/expui/general/questionDialog_dark.svg?url";
import refreshLight from "./idea/expui/general/refresh.svg?url";
import refreshDark from "./idea/expui/general/refresh_dark.svg?url";
import rowsLight from "./idea/expui/general/splitHorizontally.svg?url";
import rowsDark from "./idea/expui/general/splitHorizontally_dark.svg?url";
import runToolWindowLight from "./idea/expui/toolwindows/run.svg?url";
import runToolWindowDark from "./idea/expui/toolwindows/run_dark.svg?url";
import runToolWindowLargeLight from "./idea/expui/toolwindows/run@20x20.svg?url";
import runToolWindowLargeDark from "./idea/expui/toolwindows/run@20x20_dark.svg?url";
import scissorsLight from "./idea/expui/general/cut.svg?url";
import scissorsDark from "./idea/expui/general/cut_dark.svg?url";
import sidebarSimpleLight from "./idea/expui/general/layout.svg?url";
import sidebarSimpleDark from "./idea/expui/general/layout_dark.svg?url";
import signOutLight from "./idea/expui/general/exit.svg?url";
import signOutDark from "./idea/expui/general/exit_dark.svg?url";
import stopLight from "./idea/expui/run/stop.svg?url";
import stopDark from "./idea/expui/run/stop_dark.svg?url";
import tableLight from "./idea/expui/nodes/dataTables.svg?url";
import tableDark from "./idea/expui/nodes/dataTables_dark.svg?url";
import terminalWindowLight from "./idea/expui/toolwindows/terminal.svg?url";
import terminalWindowDark from "./idea/expui/toolwindows/terminal_dark.svg?url";
import terminalWindowLargeLight from "./idea/expui/toolwindows/terminal@20x20.svg?url";
import terminalWindowLargeDark from "./idea/expui/toolwindows/terminal@20x20_dark.svg?url";
import translateLight from "./idea/expui/general/language.svg?url";
import translateDark from "./idea/expui/general/language_dark.svg?url";
import trashLight from "./idea/expui/general/delete.svg?url";
import trashDark from "./idea/expui/general/delete_dark.svg?url";
import treeStructureLight from "./idea/expui/general/tree.svg?url";
import treeStructureDark from "./idea/expui/general/tree_dark.svg?url";
import uploadLight from "./idea/expui/general/upload.svg?url";
import uploadDark from "./idea/expui/general/upload_dark.svg?url";
import uploadSimpleLight from "./idea/expui/general/upload.svg?url";
import uploadSimpleDark from "./idea/expui/general/upload_dark.svg?url";
import userLight from "./idea/expui/general/user.svg?url";
import userDark from "./idea/expui/general/user_dark.svg?url";
import usersThreeLight from "./idea/expui/general/groups.svg?url";
import usersThreeDark from "./idea/expui/general/groups_dark.svg?url";
import vcsLight from "./idea/expui/general/vcs.svg?url";
import vcsDark from "./idea/expui/general/vcs_dark.svg?url";
import warningCircleLight from "./idea/expui/general/warningDialog.svg?url";
import warningCircleDark from "./idea/expui/general/warningDialog_dark.svg?url";
import warningLight from "./idea/expui/general/warningDialog.svg?url";
import warningDark from "./idea/expui/general/warningDialog_dark.svg?url";
import wrenchLight from "./idea/expui/general/externalTools.svg?url";
import wrenchDark from "./idea/expui/general/externalTools_dark.svg?url";
import xCircleLight from "./idea/expui/general/errorDialog.svg?url";
import xCircleDark from "./idea/expui/general/errorDialog_dark.svg?url";
import xLight from "./idea/expui/general/close.svg?url";
import xDark from "./idea/expui/general/close_dark.svg?url";

export interface IdeaIconAsset {
  light: string;
  dark: string;
  /** IntelliJ @20x20 toolbar and stripe artwork, when it exists. */
  large?: { light: string; dark: string };
}

export const ideaIconAssets: Record<string, IdeaIconAsset> = {
  ArchiveIcon: { light: archiveLight, dark: archiveDark },
  ArrowClockwiseIcon: { light: arrowClockwiseLight, dark: arrowClockwiseDark },
  ArrowCounterClockwiseIcon: { light: arrowCounterClockwiseLight, dark: arrowCounterClockwiseDark },
  ArrowDownIcon: { light: arrowDownLight, dark: arrowDownDark },
  ArrowLeftIcon: { light: arrowLeftLight, dark: arrowLeftDark },
  ArrowRightIcon: { light: arrowRightLight, dark: arrowRightDark },
  ArrowSquareOutIcon: { light: arrowSquareOutLight, dark: arrowSquareOutDark },
  ArrowUpIcon: { light: arrowUpLight, dark: arrowUpDark },
  BalloonErrorIcon: { light: balloonErrorLight, dark: balloonErrorDark },
  BellIcon: { light: bellLight, dark: bellDark, large: { light: bellLargeLight, dark: bellLargeDark } },
  BookmarkIcon: { light: bookmarkLight, dark: bookmarkDark },
  BookOpenIcon: { light: bookOpenLight, dark: bookOpenDark },
  BugIcon: { light: bugLight, dark: bugDark },
  CaretDownIcon: { light: caretDownLight, dark: caretDownDark },
  CaretLeftIcon: { light: caretLeftLight, dark: caretLeftDark },
  CaretRightIcon: { light: caretRightLight, dark: caretRightDark },
  CaretUpIcon: { light: caretUpLight, dark: caretUpDark },
  ChatCircleTextIcon: { light: chatCircleTextLight, dark: chatCircleTextDark },
  CheckCircleIcon: { light: checkCircleLight, dark: checkCircleDark },
  CheckIcon: { light: checkLight, dark: checkDark },
  ChevronDownIcon: { light: chevronDownLight, dark: chevronDownDark },
  ChevronLeftIcon: { light: chevronLeftLight, dark: chevronLeftDark },
  ChevronRightIcon: { light: chevronRightLight, dark: chevronRightDark },
  ChevronUpIcon: { light: chevronUpLight, dark: chevronUpDark },
  ClockCounterClockwiseIcon: { light: clockCounterClockwiseLight, dark: clockCounterClockwiseDark },
  ColumnsIcon: { light: columnsLight, dark: columnsDark },
  CopyIcon: { light: copyLight, dark: copyDark },
  CopySimpleIcon: { light: copySimpleLight, dark: copySimpleDark },
  DatabaseIcon: { light: databaseLight, dark: databaseDark },
  DotsThreeIcon: { light: dotsThreeLight, dark: dotsThreeDark },
  DownloadIcon: { light: downloadLight, dark: downloadDark },
  DownloadSimpleIcon: { light: downloadSimpleLight, dark: downloadSimpleDark },
  EyeIcon: { light: eyeLight, dark: eyeDark },
  EyeSlashIcon: { light: eyeSlashLight, dark: eyeSlashDark },
  FileIcon: { light: fileLight, dark: fileLight },
  FilePlusIcon: { light: filePlusLight, dark: filePlusDark },
  FilesIcon: { light: filesLight, dark: filesDark, large: { light: filesLargeLight, dark: filesLargeDark } },
  FileTextIcon: { light: fileTextLight, dark: fileTextLight },
  FloppyDiskIcon: { light: floppyDiskLight, dark: floppyDiskDark },
  FolderIcon: { light: folderLight, dark: folderDark },
  FolderPlusIcon: { light: folderPlusLight, dark: folderPlusDark },
  FunctionIcon: { light: functionLight, dark: functionDark },
  FunnelIcon: { light: funnelLight, dark: funnelDark },
  GearIcon: { light: gearLight, dark: gearDark, large: { light: gearLargeLight, dark: gearLargeDark } },
  GearSixIcon: { light: gearSixLight, dark: gearSixDark },
  GitBranchIcon: { light: gitBranchLight, dark: gitBranchDark },
  GitCommitIcon: { light: gitCommitLight, dark: gitCommitDark, large: { light: gitCommitLargeLight, dark: gitCommitLargeDark } },
  GitDiffIcon: { light: gitDiffLight, dark: gitDiffDark },
  GitGraphIcon: { light: gitGraphLight, dark: gitGraphDark, large: { light: gitGraphLargeLight, dark: gitGraphLargeDark } },
  GitMergeIcon: { light: gitMergeLight, dark: gitMergeDark },
  GlobeHemisphereWestIcon: { light: globeHemisphereWestLight, dark: globeHemisphereWestDark },
  GlobeIcon: { light: globeLight, dark: globeDark },
  HashIcon: { light: hashLight, dark: hashDark },
  HouseIcon: { light: houseLight, dark: houseDark },
  ImageIcon: { light: imageLight, dark: imageDark },
  InfoIcon: { light: infoLight, dark: infoDark },
  KeyboardIcon: { light: keyboardLight, dark: keyboardDark },
  LightbulbIcon: { light: lightbulbLight, dark: lightbulbDark },
  LightningIcon: { light: lightningLight, dark: lightningDark },
  LockIcon: { light: lockLight, dark: lockDark },
  LockOpenIcon: { light: lockOpenLight, dark: lockOpenDark },
  MagnifyingGlassIcon: { light: magnifyingGlassLight, dark: magnifyingGlassDark, large: { light: magnifyingGlassLargeLight, dark: magnifyingGlassLargeDark } },
  MagnifyingGlassMinusIcon: { light: magnifyingGlassMinusLight, dark: magnifyingGlassMinusDark },
  MagnifyingGlassPlusIcon: { light: magnifyingGlassPlusLight, dark: magnifyingGlassPlusDark },
  MenuIcon: { light: menuLight, dark: menuDark, large: { light: menuLargeLight, dark: menuLargeDark } },
  MinusIcon: { light: minusLight, dark: minusDark },
  MonitorIcon: { light: monitorLight, dark: monitorDark },
  OpenExternalIcon: { light: openExternalLight, dark: openExternalDark },
  PaletteIcon: { light: paletteLight, dark: paletteDark },
  PauseIcon: { light: pauseLight, dark: pauseDark },
  PencilIcon: { light: pencilLight, dark: pencilDark },
  PencilLineIcon: { light: pencilLineLight, dark: pencilLineDark },
  PencilSimpleIcon: { light: pencilSimpleLight, dark: pencilSimpleDark },
  PencilSimpleLineIcon: { light: pencilSimpleLineLight, dark: pencilSimpleLineDark },
  PenIcon: { light: penLight, dark: penDark },
  PlayIcon: { light: playLight, dark: playDark },
  PlusIcon: { light: plusLight, dark: plusDark },
  ProblemsToolWindowIcon: { light: problemsToolWindowLight, dark: problemsToolWindowDark, large: { light: problemsToolWindowLargeLight, dark: problemsToolWindowLargeDark } },
  PushPinIcon: { light: pushPinLight, dark: pushPinDark },
  QuestionIcon: { light: questionLight, dark: questionDark },
  RefreshIcon: { light: refreshLight, dark: refreshDark },
  RowsIcon: { light: rowsLight, dark: rowsDark },
  RunToolWindowIcon: { light: runToolWindowLight, dark: runToolWindowDark, large: { light: runToolWindowLargeLight, dark: runToolWindowLargeDark } },
  ScissorsIcon: { light: scissorsLight, dark: scissorsDark },
  SidebarSimpleIcon: { light: sidebarSimpleLight, dark: sidebarSimpleDark },
  SignOutIcon: { light: signOutLight, dark: signOutDark },
  StopIcon: { light: stopLight, dark: stopDark },
  TableIcon: { light: tableLight, dark: tableDark },
  TerminalWindowIcon: { light: terminalWindowLight, dark: terminalWindowDark, large: { light: terminalWindowLargeLight, dark: terminalWindowLargeDark } },
  TranslateIcon: { light: translateLight, dark: translateDark },
  TrashIcon: { light: trashLight, dark: trashDark },
  TreeStructureIcon: { light: treeStructureLight, dark: treeStructureDark },
  UploadIcon: { light: uploadLight, dark: uploadDark },
  UploadSimpleIcon: { light: uploadSimpleLight, dark: uploadSimpleDark },
  UserIcon: { light: userLight, dark: userDark },
  UsersThreeIcon: { light: usersThreeLight, dark: usersThreeDark },
  VcsIcon: { light: vcsLight, dark: vcsDark },
  WarningCircleIcon: { light: warningCircleLight, dark: warningCircleDark },
  WarningIcon: { light: warningLight, dark: warningDark },
  WrenchIcon: { light: wrenchLight, dark: wrenchDark },
  XCircleIcon: { light: xCircleLight, dark: xCircleDark },
  XIcon: { light: xLight, dark: xDark },
};
